
export const FETCH_DUTCH_ADD_RECEIPTS = 'FETCH_DUTCH_ADD_RECEIPTS';
export const FETCH_DUTCH_ADD_RECEIPTS_FULFILLED = `${FETCH_DUTCH_ADD_RECEIPTS}_FULFILLED`;
export const FETCH_DUTCH_ADD_RECEIPTS_REJECTED = `${FETCH_DUTCH_ADD_RECEIPTS}_REJECTED`;
export const FETCH_DUTCH_ADD_RECEIPTS_PENDING = `${FETCH_DUTCH_ADD_RECEIPTS}_PENDING`;

export const FETCH_DUTCH_BID_RECEIPTS = 'FETCH_DUTCH_BID_RECEIPTS';
export const FETCH_DUTCH_BID_RECEIPTS_FULFILLED = `${FETCH_DUTCH_BID_RECEIPTS}_FULFILLED`;
export const FETCH_DUTCH_BID_RECEIPTS_REJECTED = `${FETCH_DUTCH_BID_RECEIPTS}_REJECTED`;
export const FETCH_DUTCH_BID_RECEIPTS_PENDING = `${FETCH_DUTCH_BID_RECEIPTS}_PENDING`;

export const FETCH_ENGLISH_ADD_RECEIPTS = 'FETCH_ENGLISH_ADD_RECEIPTS';
export const FETCH_ENGLISH_ADD_RECEIPTS_FULFILLED = `${FETCH_ENGLISH_ADD_RECEIPTS}_FULFILLED`;
export const FETCH_ENGLISH_ADD_RECEIPTS_REJECTED = `${FETCH_ENGLISH_ADD_RECEIPTS}_REJECTED`;
export const FETCH_ENGLISH_ADD_RECEIPTS_PENDING = `${FETCH_ENGLISH_ADD_RECEIPTS}_PENDING`;

export const FETCH_ENGLISH_BID_RECEIPTS = 'FETCH_ENGLISH_BID_RECEIPTS';
export const FETCH_ENGLISH_BID_RECEIPTS_FULFILLED = `${FETCH_ENGLISH_BID_RECEIPTS}_FULFILLED`;
export const FETCH_ENGLISH_BID_RECEIPTS_REJECTED = `${FETCH_ENGLISH_BID_RECEIPTS}_REJECTED`;
export const FETCH_ENGLISH_BID_RECEIPTS_PENDING = `${FETCH_ENGLISH_BID_RECEIPTS}_PENDING`;


export const FETCH_SEALED_BID_ADD_RECEIPTS = 'FETCH_SEALED_BID_ADD_RECEIPTS';
export const FETCH_SEALED_BID_ADD_RECEIPTS_FULFILLED = `${FETCH_SEALED_BID_ADD_RECEIPTS}_FULFILLED`;
export const FETCH_SEALED_BID_ADD_RECEIPTS_REJECTED = `${FETCH_SEALED_BID_ADD_RECEIPTS}_REJECTED`;
export const FETCH_SEALED_BID_ADD_RECEIPTS_PENDING = `${FETCH_SEALED_BID_ADD_RECEIPTS}_PENDING`;

export const FETCH_SEALED_BID_BID_RECEIPTS = 'FETCH_SEALED_BID_BID_RECEIPTS';
export const FETCH_SEALED_BID_BID_RECEIPTS_FULFILLED = `${FETCH_SEALED_BID_BID_RECEIPTS}_FULFILLED`;
export const FETCH_SEALED_BID_BID_RECEIPTS_REJECTED = `${FETCH_SEALED_BID_BID_RECEIPTS}_REJECTED`;
export const FETCH_SEALED_BID_BID_RECEIPTS_PENDING = `${FETCH_SEALED_BID_BID_RECEIPTS}_PENDING`;

export const fetchDutchAddReceipt = (username) =>({
    type: FETCH_DUTCH_ADD_RECEIPTS,
    payload: {username}
});

export const fetchDutchBidReceipts = (username) =>({
    type: FETCH_DUTCH_BID_RECEIPTS,
    payload: {username}
});

export const fetchEnglishAddReceipt = (username) =>({
    type: FETCH_ENGLISH_ADD_RECEIPTS,
    payload: {username}
});

export const fetchEnglishBidReceipts = (username) =>({
    type: FETCH_ENGLISH_BID_RECEIPTS,
    payload: {username}
});

export const fetchSealedBidAddReceipt = (username) =>({
    type: FETCH_SEALED_BID_ADD_RECEIPTS,
    payload: {username}
});

export const fetchSealedBidBidReceipts = (username) =>({
    type: FETCH_SEALED_BID_BID_RECEIPTS,
    payload: {username}
});
